cache_dir: "../tensorleap/data/conll2003/"
gcs_project: splendid-flow-231921
gcs_bucket_name: datasets-reteai
gcs_data_dir: NER/

train_size: 5000
val_size: 3000
test_size: 1500

ul_size: 1500

max_length: 512

labels:
  - "O"       # Outside of a named entity
  - "B-PER"   # Beginning of a person’s name
  - "I-PER"   # Inside of a person’s name
  - "B-ORG"   # Beginning of an organization
  - "I-ORG"   # Inside of an organization
  - "B-LOC"   # Beginning of a location
  - "I-LOC"   # Inside of a location
  - "B-MISC"  # Beginning of a miscellaneous entity
  - "I-MISC"  # Inside of a miscellaneous entity

model_labels:
  - 'O'
  - 'B-MISC'
  - 'I-MISC'
  - 'B-PER'
  - 'I-PER'
  - 'B-ORG'
  - 'I-ORG'
  - 'B-LOC'
  - 'I-LOC'


categories:
  - "O"     # Outside of a named entity
  - "PER"   # person’s name
  - "ORG"   # organization
  - "LOC"   # location
  - "MISC"  # miscellaneous entity

"O": 0
"B-MISC": 1,
"I-MISC": 2,
"B-PER": 3,
"I-PER": 4,
"B-ORG": 5,
"I-ORG": 6,
"B-LOC": 7,
"I-LOC": 8,

special_token_id: -100
CLS_ID: 101
SEP_ID: 102
